### ISSUE TITLE
стилізація посилання

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-8-user-card#1]
https://github.com/BohdanLuts/home-work-lesson-8-user-card/blob/7ffdad6ccc35dfbe8336b7302530bee83a002b75/index.html#L82
- не варто вкладати блочний p в рядковий a. Якщо питання в тому, що відступи некоректно відпрацьовують, то варто стилити саму лінку, і зробити її блочною `display: block`

**Comment by BohdanLuts** [comment]
Використав. Завдяки display: block стилі повернулися.
